README.md, doc/CDN_Transcode_Sample_Getting_Started_Guide.md
-  Add System Requirements
-  Add How to Contribute
-  Add How to Report Bugs
-  Update auto deploy
-  Update http link to https
=> Update README.md and getting started guide

README.md
Signed-off-by: Zhou, Cheng <cheng.zhou@intel.com>
=> Fix issue link in README

cdn-server/.dockerignore, cdn-server/Dockerfile, cdn-server/self-sign.sh, doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Add Nginx SSL certificates for manual deploy

doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Update manual deploy steps in user guide

doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Add some notes into getting started guide

doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Update auto deploy steps in getting started guide

.travis.yml, README.md
Add travis yml to enable build on each commit
=> enable travis CI

volume/html/header.shtml, volume/html/index.html
Signed-off-by: Mingyang Wu <mingyangx.wu@intel.com>
=> Change index page title to "CDN Transcode Sample"

doc/CDN_Transcode_Sample_Getting_Started_Guide.md
Signed-off-by: Zhou, Cheng <cheng.zhou@intel.com>
=> Update getting started guide

doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Add HLS ABR configuation into getting started guide

cdn-server/messaging.py, deployment/docker-swarm/docker-compose.yml, xcode-server/ffmpeg-hw/messaging.py, xcode-server/ffmpeg-hw/zkstate.py, xcode-server/ffmpeg-sw/messaging.py, xcode-server/ffmpeg-sw/zkstate.py
=> Updated docker-compose.yml

deployment/docker-swarm/docker-compose.yml, doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Updated zookeeper and kafka docker images

deployment/kubernetes/CMakeLists.txt, deployment/kubernetes/docker-compose-template.yml, deployment/kubernetes/start.sh, deployment/kubernetes/stop.sh, deployment/kubernetes/update_yaml.py
=> Integrate with kubernetes

deployment/kubernetes/start.sh, deployment/kubernetes/update_yaml.py
=> Increased CDN kubernetes script stability

.travis.yml, content-provider/CMakeLists.txt, content-provider/Dockerfile, content-provider/build.sh, content-provider/shell.sh, doc/CDN_Transcode_Sample_Getting_Started_Guide.md, xcode-server/ffmpeg-hw/build.sh, xcode-server/ffmpeg-sw/build.sh
=> Move sample video clip process into docker

README.md, doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Update user guide for CentOS support

deployment/kubernetes/update_yaml.py
Signed-off-by: mingwu123123 <mingyangx.wu@intel.com>
=> Update kubernetes configuration python script

deployment/kubernetes/dashboard/grafana.yaml, deployment/kubernetes/dashboard/heapster-admin.yaml, deployment/kubernetes/dashboard/heapster-rbac.yaml, deployment/kubernetes/dashboard/heapster.yaml, deployment/kubernetes/dashboard/influxdb.yaml, deployment/kubernetes/dashboard/kubernetes-dashboard-clusterrolebinding.yaml, deployment/kubernetes/dashboard/kubernetes-dashboard-sa.yaml, deployment/kubernetes/dashboard/kubernetes-dashboard.yaml
add the dashboard support for CDN.
Signed-off-by: Zhang, Owen <owen.zhang@intel.com>
=> [k8s] add the dashboard support for CDN

deployment/kubernetes/start.sh, deployment/kubernetes/stop.sh, deployment/kubernetes/update_yaml.py, deployment/kubernetes/yaml_utils.py, doc/CDN_Transcode_Sample_Getting_Started_Guide.md
=> Update kubernetes python script

deployment/kubernetes/docker-compose-template.yml, deployment/kubernetes/update_yaml.py, deployment/kubernetes/yaml_utils.py
=> Fix some kubernetes python script issues

streaming-server/CMakeLists.txt
=> Fix build ovc streaming service error

deployment/kubernetes/dashboard/start_dashboard.sh, deployment/kubernetes/dashboard/stop_dashboard.sh, deployment/kubernetes/dashboard/update_dashboard.py, script/Kubernetes_remove_ubuntu.sh, script/Kubernetes_setup_ubuntu_master.sh, script/Kubernetes_setup_ubuntu_node.sh, script/enable_nat.sh, script/install_dependency.sh, script/nfs_setup_ubuntu.sh
=> Add script for setup environment

deployment/kubernetes/dashboard/kubernetes-dashboard-sa.yaml, deployment/kubernetes/dashboard/kubernetes-dashboard-service.yaml, deployment/kubernetes/dashboard/monitoring-grafana-service.yaml, deployment/kubernetes/dashboard/monitoring-influxdb-service.yaml, deployment/kubernetes/dashboard/start_dashboard.sh, deployment/kubernetes/update_yaml.py, script/Kubernetes_setup_ubuntu_master.sh, script/Kubernetes_setup_ubuntu_node.sh, script/enable_gpu_plugin.sh, script/nfs_setup_ubuntu.sh
=> Change Kubernetes dashboard and CDN sample node port

deployment/kubernetes/docker-compose-template.yml, deployment/kubernetes/start.sh, deployment/kubernetes/stop.sh, deployment/kubernetes/update_yaml.py, deployment/kubernetes/yaml_utils.py, script/Kubernetes_setup_ubuntu_master.sh
=> Optimize kubernetes python script

cdn-server/nginx.conf, streaming-server/nginx.conf
=> Update nginx configuration

deployment/kubernetes/dashboard/update_dashboard.py, script/install_dependency.sh
=> Optimize Kubernetes dashboard python script

cdn-server/nginx.conf, deployment/docker-swarm/docker-compose.yml, deployment/kubernetes/docker-compose-template.yml, deployment/kubernetes/start.sh, deployment/kubernetes/stop.sh, deployment/kubernetes/yaml_utils.py, script/Kubernetes_setup_ubuntu_master.sh
=> Enhanced self certificates security on Kubernetes deployment

xcode-server/ffmpeg-hw/Dockerfile, xcode-server/ffmpeg-sw/Dockerfile
=> Enable SVT-AV1 mp4 and mkv/webm container support

script/Kubernetes_remove.sh, script/Kubernetes_setup_master.sh, script/Kubernetes_setup_node.sh, script/nfs_setup.sh
=> Add Kubernetes setup script on CentOS

cdn-server/Dockerfile, cdn-server/config.ini, cdn-server/main.py, cdn-server/nginx.conf, cdn-server/upload.py, deployment/kubernetes/yaml_utils.py, script/install_dependency.sh, volume/html/css/app.css, volume/html/header.shtml, volume/html/js/app-header.js
Signed-off-by: Mingyang Wu <mingyangx.wu@intel.com>
=> Add HTTP upload support for VOD

cdn-server/Dockerfile, cdn-server/nginx.conf
=> Replace nginx rtmp module with nginx http flv module

xcode-server/ffmpeg-hw/Dockerfile, xcode-server/ffmpeg-sw/Dockerfile
=> Upgrade SVT-AV1 to v0.6.0

deployment/kubernetes/update_yaml.py
=> Enabled independently launch VOD/Live instances by Kubernetes

cdn-server/Dockerfile, cdn-server/main.py, cdn-server/tasks.py, cdn-server/upload.py, deployment/docker-swarm/docker-compose.yml, deployment/kubernetes/docker-compose-template.yml, deployment/kubernetes/update_yaml.py, script/install_dependency.sh, volume/html/js/app-header.js
Signed-off-by: mingwu123123 <mingyangx.wu@intel.com>
=> change upload module and increase asynchronous task processing

cdn-server/main.py
Run celery process  in the background
=> Run celery process  in the background

cdn-server/Dockerfile, xcode-server/Dockerfile
=> Enabled SVT-AV1 RTMP and DASH support on Nginx HTTP FLV module

cdn-server/Dockerfile
=> Replaced pip install with apt-get install.

script/Kubernetes_setup_master.sh, script/Kubernetes_setup_node.sh
=> Limited Kubernetes version to v1.15.3

cdn-server/Dockerfile, streaming-server/Dockerfile, xcode-server/Dockerfile
=> Use archived CDN patches from v0.1

deployment/docker-swarm/docker-compose.yml
=> Update docker swarm configuration

deployment/kubernetes/update_yaml.py, deployment/kubernetes/yaml_utils.py
=> Add workaround for picture size limitation on SVT AV1

deployment/kubernetes/update_yaml.py
=> Prevent arbitrary command inject issue

script/Kubernetes_setup_master.sh, script/Kubernetes_setup_node.sh
=> Fix the problem that the node is not ready after restart

cdn-server/Dockerfile
=> Upgrade Nginx and Nginx HTTP FLV module

cdn-server/Dockerfile, cdn-server/build.sh, cdn-server/nginx.conf, deployment/docker-swarm/docker-compose.yml, deployment/docker-swarm/start.sh, deployment/kubernetes/yaml_utils.py
=> Enhance the network security of Nginx

cdn-server/tasks.py
=> Fix clips capture issue on upload module

deployment/kubernetes/docker-compose-template.yml, deployment/kubernetes/frame_config.py, deployment/kubernetes/frame_index.py, deployment/kubernetes/run_with_GUI.py, deployment/kubernetes/run_with_command.py, deployment/kubernetes/start_GUI.sh, deployment/kubernetes/update_yaml.py, deployment/kubernetes/yaml_utils.py, script/install_dependency.sh, xcode-server/Dockerfile
=> Specify CPU and memory resources by Kubernetes

cdn-server/Dockerfile, xcode-server/Dockerfile
=> Upgrade SVT-AV1 and Nginx-http-flv-module

deployment/kubernetes/alerting/prometheus/rules.yaml
=> Update prometheus monitoring rules

cdn-server/build.sh, deployment/docker-swarm/start.sh, deployment/kubernetes/start.sh, deployment/kubernetes/start_GUI.sh
=> Fix Travis CI build error

script/Kubernetes_setup_master.sh, script/Kubernetes_setup_node.sh, script/install_dependency.sh
update README and create new doc files
=> update install enviromment script

README.md, doc/Remove_the_Kubernetes_environment.md, doc/Set_proxy_server.md, doc/Setup_Kubernetes_master_environment.md, doc/Setup_Kubernetes_master_environment_CentOS.md, doc/Setup_Kubernetes_master_environment_ubuntu.md, doc/Setup_Kubernetes_slaver_node_environment.md, doc/Setup_NFS_server_or_client.md, doc/Start_CDN_Transcode_Sample.md, script/install_dependency.sh
update README and enviroment install script
=> update README and enviroment install script

cdn-server/Dockerfile, cdn-server/config.ini, cdn-server/main.py, cdn-server/messaging.py, cdn-server/playlist.py, cdn-server/schedule.py, cdn-server/upload.py, xcode-server/hardware/Dockerfile, xcode-server/hardware/abr_hls_dash.py, xcode-server/hardware/config.ini, xcode-server/hardware/main.py, xcode-server/hardware/messaging.py, xcode-server/hardware/zkstate.py, xcode-server/software/Dockerfile, xcode-server/software/abr_hls_dash.py, xcode-server/software/config.ini, xcode-server/software/main.py, xcode-server/software/messaging.py, xcode-server/software/zkstate.py
=> Optimized the python scripts

cdn-server/Dockerfile, streaming-server/Dockerfile, xcode-server/hardware/Dockerfile, xcode-server/software/Dockerfile
=> Upgrade OpenVisualCloud docker images to v20.3.1

.gitignore, CMakeLists.txt, deployment/kubernetes/CMakeLists.txt, deployment/kubernetes/build.sh, deployment/kubernetes/cdn-service-deployment.yaml.m4, deployment/kubernetes/cdn-service-service.yaml.m4, deployment/kubernetes/kafka-service-deployment.yaml.m4, deployment/kubernetes/kafka-service-service.yaml.m4, deployment/kubernetes/live-service-deployment.yaml.m4, deployment/kubernetes/redis-service-deployment.yaml.m4, deployment/kubernetes/redis-service-service.yaml.m4, deployment/kubernetes/run_with_command.py, deployment/kubernetes/start.sh, deployment/kubernetes/stop.sh, deployment/kubernetes/update_yaml.py, deployment/kubernetes/vod-service-deployment.yaml.m4, deployment/kubernetes/yaml_utils.py, deployment/kubernetes/zookeeper-service-deployment.yaml.m4, deployment/kubernetes/zookeeper-service-service.yaml.m4, script/deployment.cmake, script/service.cmake
Signed-off-by: Gu,YingX <yingx.gu@intel.com>
=> Update the script for reslove the config files

deployment/kubernetes/build.sh, deployment/kubernetes/cdn-service-deployment.yaml.m4, deployment/kubernetes/kafka-service-deployment.yaml.m4, deployment/kubernetes/live-service-deployment.yaml.m4, deployment/kubernetes/logging/start_logging.sh, deployment/kubernetes/monitoring/grafana/grafana-deploy.yaml, deployment/kubernetes/monitoring/heapster/heapster-deploy.yaml, deployment/kubernetes/monitoring/node-export/node-exporter-deploy.yaml, deployment/kubernetes/monitoring/prometheus/prometheus-deploy.yaml, deployment/kubernetes/monitoring/start_monitoring.sh, deployment/kubernetes/redis-service-deployment.yaml.m4, deployment/kubernetes/vod-service-deployment.yaml.m4, deployment/kubernetes/yaml_utils.py, deployment/kubernetes/zookeeper-service-deployment.yaml.m4, script/Kubernetes_remove.sh, script/Kubernetes_setup_master.sh, script/Kubernetes_setup_node.sh
Signed-off-by: Gu,YingX <yingx.gu@intel.com>
=> Update to Kubernetes 1.18.2

deployment/docker-swarm/start.sh, deployment/docker-swarm/stop.sh, deployment/kubernetes/run_with_command.py, deployment/kubernetes/start.sh, script/build.sh, script/shell.sh
Ideally, python code should not perform any Kubernetes operations. So we can actually run python within a container (to minimize polluting the host system with lots of 3rd party dependencies.)
=> remove sudo for docker cmds & move kubectl out of python code
